# Done
reader_base_info ={
    'ar':{
        'dir':'rtl',
        'page_title':'البوابة العلمية',
        'mainpage':'الرئيسية',
        'archive':'الأرشيف',
        'subscribe':'اشترك الآن',
        'search':'بحث',
        'login':'دخول',
        'language':'تغيير اللغة',
        'login_as':'التسجيل كـ',
        'EIC':'رئيس مجلس التحرير',
        'AE':'محرر',
        'writer':'كاتب',
        'reviewer':'مراجع',
        'subscriber':'مشترك',
        'email':'البريد الإلكتروني',
        'password':'كلمة المرور',
        'sign_in':'تسجيل الدخول',
        'forget_pass':'نسيت كلمة المرور؟',
        'register_as_writer':'التسجيل ككاتب جديد؟',
        'health':'الصحة',
        'IT':'تقنية المعلومات',
        'ecology':'البيئة',
        'organisms':'الحياة',
        'nature':'الطبيعة و الكون',
        'chemicals':'كيميائيات',
        'math':'رياضيات',
        'engineering':'هندسيات',
        
        'policy':'سياسة البوابة العلمية',
        'keep_touch':'ابقى على تواصل معنا',
        'categories':'الأقسام',
        'about_us':'نحن نسعى من خلال هذه البوابة تقديم كل ماهو مفيد وحصري في مجالي العلوم و الهندسة\n هدفنا هو رفع الوعي وذلك بتبسيع المعرفة و العلوم',
    },
    'en':{
        'dir':'ltr',
        'page_title':'Scientific Gate',
        'mainpage':'Mainpage',
        'archive':'Archive',
        'subscribe':'Subscribe',
        'search':'Search',
        'login':'Sign in',
        'language':'Language',
        'login_as':'Sign in as:',
        'EIC':'Editor-in-Chief',
        'AE':'Associated Editor',
        'writer':'Writer',
        'reviewer':'Reviewer',
        'subscriber':'Subscriber',
        'email':'Email',
        'password':'Password',
        'sign_in':'Sign in',
        'forget_pass':'forget password ?',
        'register_as_writer':'register as a new writer',
        'health':'Health',
        'IT':'Information Technology',
        'ecology':'Ecology',
        'organisms':'Organisms',
        'nature':'Nature',
        'chemicals':'Chemicals',
        'math':'Math',
        'engineering':'Engineering',
        'latest_article':'Latest Articles',
        'no_articles':'There is no articles in this section',
        'most_read':'Most Readed Articles',
        'highest_rate':'Highest Rated Articles',
        'read_more':'... read more',
        'quick_search_in_archive':'Quick Search in Archive',
        'search_from':'search from : ',
        'search_to':'search to : ',
        'choose_search_field':'please choose field',
        'policy':'Scientific Gate Policy',
        'keep_touch':'Keep on Touch',
        'categories':'categories',
        'about_us':'We are targeting people they locking for knowlagde but in simple ways',
    }
}

writer_base_info ={
    'ar':{
        'dir':'rtl',
        'page_title':'البوابة العلمية - كاتب',
        'mainpage':'الرئيسية',
        'archive':'الأرشيف',
        'create_new_article':'أنشئ مقالة جديدة',
        'search':'بحث',
        'my_profile':'ملف التعريف',
        'language':'تغيير اللغة',
        'logout':'تسجيل الخروج',
        'all_my_articles':'مقالاتي',
        'health':'الصحة',
        'IT':'تقنية المعلومات',
        'ecology':'البيئة',
        'organisms':'الحياة',
        'nature':'الطبيعة و الكون',
        'chemicals':'كيميائيات',
        'math':'رياضيات',
        'engineering':'هندسيات',
        'policy':'سياسة البوابة العلمية',
        'keep_touch':'ابقى على تواصل معنا',
        'categories':'الأقسام',
        'about_us':'نحن نسعى من خلال هذه البوابة تقديم كل ماهو مفيد وحصري في مجالي العلوم و الهندسة\n هدفنا هو رفع الوعي وذلك بتبسيع المعرفة و العلوم',
    },
    'en':{
        'dir':'ltr',
        'page_title':'Scientific Gate - Writer',
        'mainpage':'Mainpage',
        'archive':'Archive',
        'create_new_article':'New Article',
        'search':'search',
        'my_profile':'My Profile',
        'language':'Language',
        'logout':'Logout',
        'all_my_articles':'My Articles',
        'health':'Health',
        'IT':'Information Technology',
        'ecology':'Ecology',
        'organisms':'Organisms',
        'nature':'Nature',
        'chemicals':'Chemicals',
        'math':'Math',
        'engineering':'Engineering',
        'policy':'Scientific Gate Policy',
        'keep_touch':'Keep on Touch',
        'categories':'categories',
        'about_us':'We are targeting people they locking for knowlagde but in simple ways',
    }
}

subscriber_base_info ={
    'ar':{
        'dir':'rtl',
        'page_title':'البوابة العلمية - مشترك',
        'mainpage':'الرئيسية',
        'archive':'الأرشيف',
        'search':'بحث',
        'my_profile':'ملف التعريف',
        'language':'تغيير اللغة',
        'logout':'تسجيل الخروج',
        'health':'الصحة',
        'IT':'تقنية المعلومات',
        'ecology':'البيئة',
        'organisms':'الحياة',
        'nature':'الطبيعة و الكون',
        'chemicals':'كيميائيات',
        'math':'رياضيات',
        'engineering':'هندسيات',
        'policy':'سياسة البوابة العلمية',
        'keep_touch':'ابقى على تواصل معنا',
        'categories':'الأقسام',
        'about_us':'نحن نسعى من خلال هذه البوابة تقديم كل ماهو مفيد وحصري في مجالي العلوم و الهندسة\n هدفنا هو رفع الوعي وذلك بتبسيع المعرفة و العلوم',
    },
    'en':{
        'dir':'ltr',
        'page_title':'Scientific Gate - Subscriber',
        'mainpage':'Mainpage',
        'archive':'Archive',
        'search':'search',
        'language':'Language',
        'my_profile':'My Profile',
        'logout':'Logout',
        'health':'Health',
        'IT':'Information Technology',
        'ecology':'Ecology',
        'organisms':'Organisms',
        'nature':'Nature',
        'chemicals':'Chemicals',
        'math':'Math',
        'engineering':'Engineering',
        'policy':'Scientific Gate Policy',
        'keep_touch':'Keep on Touch',
        'categories':'categories',
        'about_us':'We are targeting people they locking for knowlagde but in simple ways',
    }
}

home_articles_info ={
    'ar':{
        'latest_article':'أحدث المقالات',
        'no_articles':'لا توجد مقالات متوفرة في هذا القسم',
        'most_read':'الأكثر قراءة',
        'highest_rate':'الأعلى تقييماً',
        'read_more':'... قراءة المزيد',
        'quick_search_in_archive':'البحث السريع في الأرشيف',
        'search_from':'البحث من : ',
        'search_to':'البحث إلى : ',
        'choose_search_field':'الرجاء اختيار مجال البحث',
    },
    'en':{
        'latest_article':'Latest Articles',
        'no_articles':'There is no articles in this section',
        'most_read':'Most Readed Articles',
        'highest_rate':'Highest Rated Articles',
        'read_more':'... read more',
        'quick_search_in_archive':'Quick Search in Archive',
        'search_from':'search from : ',
        'search_to':'search to : ',
        'choose_search_field':'please choose field',
    }
}

show_article_info ={
    'ar':{
        'latest_articles_header':'أحدث المقالات',
        'our_writers_header':'مِن كتابنا',
        'related_articles_header':'مقالات ذات صلة',
        'no_comments':'لا توجد تعليقات على هذه المقالة',
        'to_get_priced_article':'للحصول على المقالة كاملة عليك أن تختار',
        'subscribe_now':'اشترك الآن',
        'buy_article':'اشتري المقالة ( {} ) ر.س',
        'payment_info':'بيانات الدفع',
        'card_number':'رقم البطاقة',
        'CVC':'رمز CVC',
        'expiration_date':'تاريخ إنتهاء البطاقة',
        'name_on_card':'الاسم على البطاقة',
        'email':'البريد الإلكتروني',
        'pay':'دفع رسوم المقالة',
        'about_writer':'عن الكاتب',
        'writer_info':'البيانات الشخصية',
        'comments_header':'التعليقات',
    },
    'en':{
        'latest_articles_header':'Latest Articles',
        'our_writers_header':'Our Writers',
        'related_articles_header':'Related Articles',
        'no_comments':'There is no comments yet',
        'to_get_priced_article':'Choose to get access to full article',
        'subscribe_now':'Subscribe now',
        'buy_article':'Buy article ( {} ) S.R.',
        'payment_info':'Payment Information',
        'card_number':'Card Number',
        'CVC':'CVC code',
        'expiration_date':'Expiration Date',
        'name_on_card':'Name On Card',
        'email':'Email',
        'pay':'Pay to get',
        'about_writer':'About Writer',
        'writer_info':'Writer Information',
        'comments_header':'Comments',
    }
}

subscriber_show_article_info ={
    'ar':{
        'latest_articles_header':'أحدث المقالات',
        'our_writers_header':'مِن كتابنا',
        'related_articles_header':'مقالات ذات صلة',
        'no_comments':'لا توجد تعليقات على هذه المقالة',
        'rate_this_article':'قيم محتوى المقالة : ',
        'leave_comment':'ضع تعليقاً مناسباً',
        'comment_note':'* تعليقك يجب أن لا يقل عن 10 أحرف لا يزيد عن 500 حرف',
        'about_writer':'عن الكاتب',
        'writer_info':'البيانات الشخصية',
        'comments_header':'التعليقات',
        'add_comment':'إضافة التعليق',
        'leave_first_comment':'شاركنا بأول تعليق على المقالة'
    },
    'en':{
        'latest_articles_header':'Latest Articles',
        'our_writers_header':'Our Writers',
        'related_articles_header':'Related Articles',
        'no_comments':'There is no comments yet',
        'rate_this_article':'Rate this article content',
        'leave_comment':'Leave an appropriate comment',
        'comment_note':'* Comment should be not exceed 500 character and less than 50.',
        'about_writer':'About Writer',
        'writer_info':'Writer Information',
        'comments_header':'Comments',
        'add_comment':'Comment',
        'leave_first_comment':'Leave the first comment on this article'
    }
}

field_articles_info ={
    'ar':{
        'search_in_field':'فلتر النتائج ',
        'in':'في',
        'no_articles':'لا توجد مقالات أونلاين متاحة',
        'latest_articles_header':'أحدث المقالات',
        'our_writers_header':'مِن كتابنا',
        'related_articles_header':'مقالات ذا صلة',
    },
    'en':{
        'search_in_field':'filter the results ',
        'in':'in',
        'no_articles':'There is no articles online avaliable',
        'latest_articles_header':'Latest Articles',
        'our_writers_header':'Our writer',
        'related_articles_header':'Related Articles',
    }
}

subscribe_info={
    'ar':{
        'page_title':'مشترك جديد',
        'dir':'rtl',
        'title':'التسجيل كـ(مشترك) جديد',
        'first_name':'الاسم الأول',
        'last_name':'الاسم الأخير',
        'birthdate':'تاريخ الميلاد',
        'gender':'الجنس',
        'male':'ذكر',
        'female':'انثى',
        'Email':'البريد الالكتروني',
        'phone':'الجوال',
        'country':'البلد',
        'city':'المدينة',
        'password':'كلمة المرور',
        'confirm_password':'تأكيد كلمة المرور',
        'personal_photo':'الصورة الشخصية',
        'image_field':'اختيار الصورة الشخصية',
        'package_title':'اختر الباقة المناسبة',
        'payment_info':'بيانات الدفع',
        'card_number':'رقم البطاقة',
        'CVC':'رمز CVC',
        'expiration_date':'تاريخ إنتهاء البطاقة',
        'name_on_card':'الاسم على البطاقة',        
        'register':'اشتراك',
        'have_account':'هل لديك حساب بالفعل ؟ ',
        'back':'العودة للصفحة الرئيسية',
    },
    'en':{
        'page_title':'New Subscriber',
        'dir':'ltr',
        'title':'Register As A New Subscriber',
        'first_name':'First Name',
        'last_name':'Last Name',
        'birthdate':'Birthdate',
        'gender':'Gender',
        'male':'Male',
        'female':'Female',
        'Email':'Email',
        'phone':'Phone number',
        'country':'Country',
        'city':'City',
        'password':'Password',
        'confirm_password':'confirm Password',
        'personal_photo':'Personal Photo',
        'image_field':'Choose Personal Photo',
        'package_title':'Choose Appropriate Package',
        'payment_info':'Payment Information',
        'card_number':'Card Number',
        'CVC':'CVC code',
        'expiration_date':'Expiration Date',
        'name_on_card':'Name On Card',
        'register':'Subscribe',
        'have_account':'Do you already have an account?',
        'back':'Back to mainpage',
    }
}

register_info ={
    'ar':{
        'page_title':'تسجيل ناشر جديد',
        'dir':'rtl',
        'title':'التسجيل كـ(كاتب) محتوى',
        'first_name':'الاسم الأول',
        'last_name':'الاسم الأخير',
        'birthdate':'تاريخ الميلاد',
        'gender':'الجنس',
        'male':'ذكر',
        'female':'انثى',
        'Email':'البريد الالكتروني',
        'phone':'الجوال',
        'speciality':'المجال/التخصص',
        'workplace':'مكان العمل',
        'country':'البلد',
        'city':'المدينة',
        'password':'كلمة المرور',
        'confirm_password':'تأكيد كلمة المرور',
        'personal_photo':'الصورة الشخصية',
        'image_field':'اختيار الصورة الشخصية',
        'register':'تسجيل',
        'have_account':'هل لديك حساب بالفعل ؟ ',
        'back':'العودة للصفحة الرئيسية',
    },
    'en':{
        'page_title':'New Writer',
        'dir':'ltr',
        'title':'Register As A New Writer',
        'first_name':'First Name',
        'last_name':'Last Name',
        'birthdate':'Birthdate',
        'gender':'Gender',
        'male':'Male',
        'female':'Female',
        'Email':'Email',
        'phone':'Phone number',
        'speciality':'Speciality',
        'workplace':'Workplace',
        'country':'Country',
        'city':'City',
        'password':'Password',
        'confirm_password':'confirm Password',
        'personal_photo':'Personal Photo',
        'image_field':'Choose Personal Photo',
        'register':'Register',
        'have_account':'Do you already have an account?',
        'back':'Back to mainpage',
    }
}

my_articles_info ={
    'ar':{
        'article':'المقالة',
        'field':'القسم',
        'status':'حالة المقالة',
        'submited_on':'رفعت في : ',
        'waiting':'في الانتظار',
        'reviewing':'تحت المراجعة',
        'why_rejected':'لماذا رُفضت؟',
        'why_article_rejected':'لماذا رفضت هذه المقالة ؟',
    },
    'en':{
        'article':'The Article',
        'field':'Field',
        'status':'Article Status',
        'submited_on':'Submitted on : ',
        'waiting':'Waiting',
        'reviewing':'Under Reviewing',
        'why_rejected':'Why Rejected?',
        'why_article_rejected':'Why this article has been rejected',
    }
}

new_article_info={
    'ar':{
        'page_title':'انشاء مقالة جديدة',
        'dir':'rtl',
        'title':'أنشى مقالتك الجديدة',
        'article_field':'مجال المقالة',
        'health':'الصحة',
        'IT':'تقنية المعلومات',
        'ecology':'البيئة',
        'organisms':'الحياة',
        'nature':'الطبيعة و الكون',
        'chemicals':'كيميائيات',
        'math':'رياضيات',
        'engineering':'هندسيات',
        'article_lang':'لغة المقالة',
        'arabic':'العربية',
        'english':'الانجليزية',
        'cover_image':'صورة للمقالة',
        'image_field':'اختر صورة لمقالتك',
        'article_title':'عنوان المقالة',
        'brief_of_article':'نبذة عن المقالة',
        'limitation':'يجب كتابة ما لا يقل عن 250 حرف، و لا يزيد عن 500 حرف',
        'article_body':'تفصيل المقالة',
        'article_body_tip':['- إجمالي عناصر المقالة المسموح إضافتها 6','- تستطيع إضافة 2 مقطع صوتي كحد أقصى','- تستيع إضافة 2 فيديو كحد أقصى','- حجم الفيديو الواحد يجب أن لا يتجاوز 35 MB .','- حجم مقطع الصوت الواحد يجب أن لا يتجاوز 10 MB .','- حجم الصورة الواحدة يجب أن لا يتجاوز 1 MB .','- الصيغة المقبولة لرفع الفيديوهات هي mp4 فقط','- الصيغة المقبولة لرفع المقاطع الصوتية هي mp3 فقط','- الصيغ المقبولة لرفع الصور هي ( jpeg, png, gif ) فقط','<b>- جميع الحقول إلزامية، يجب ملأها جميعها.</b>'],
        'text':'نص',
        'add_text':'إضافة نص',
        'video':'فيديو',
        'add_video':'إضافة فيديو',
        'image':'صورة',
        'add_image':'إضافة صورة',
        'audio':'صوت',
        'add_audio':'إضافة صوت',
        'register':'إرسال المقالة',
        'back':'العودة للصفحة الرئيسية',
    },
    'en':{
        'page_title':'Submit A New Article',
        'dir':'ltr',
        'title':'Create Your Article',
        'article_field':'Field of Article',
        'health':'Health',
        'IT':'Information Technology',
        'ecology':'Ecology',
        'organisms':'Organisms',
        'nature':'Nature',
        'chemicals':'Chemicals',
        'math':'Math',
        'engineering':'Engineering',
        'article_lang':'Language of Article',
        'arabic':'Arabic',
        'english':'English',
        'cover_image':'Cover Image',
        'image_field':'Choose Cover Image',
        'article_title':'Title of Article',
        'brief_of_article':'Brief of Article',
        'limitation':'should writer between 250 to 500 characters',
        'article_body':'Article Details',
        'article_body_tip':["- Total of articles' elements should be not exceed 6.",'- Maximum number of audios is 2.','- You can add just one video.','- Video size should be less than 35 MB.','- Image size should be less than 1 MB.','- Audio size should be less than 10 MB.',"- We only accept 'mp4' extension for video.","- We only accept 'mp3' extension for audio.","- We only accept ( jpeg, png, gif ) extension for video.",'<b>- All fields should be filled</b>'],
        'text':'Text',
        'add_text':'Add Text',
        'video':'Vedio',
        'add_video':'Add Video',
        'image':'Image',
        'add_image':'Add Image',
        'audio':'Audio',
        'add_audio':'Add Audio',
        'register':'Submit The Article',
        'back':' Back to the mainpage',
    }
}

activation_info={
    'ar':{
        'page_title':'انشاء مقالة جديدة',
        'dir':'rtl',
        'title':'تفعيل الحساب',
        'activation_label':'سيتم ارسال كود تفعيل إلى بريدك الالكتروني الموضح في الاعلى خلال دقائق، نرجو إدخال الكود في الخانة التالية',
        'activation_btn':'تفعيل',
    },
    'en':{
        'page_title':'Account Activation',
        'dir':'ltr',
        'title':'Account Activation',
        'activation_label':'You will receive an activation code on your email that showen above, please enter that code in the next field',
        'activation_btn':'Activate',
    },
}

activation_email_info={
    'ar':{
        'title':'تفعيل الحساب',
        'message':'كود التفعيل الخاص بحسابك هو : {}'
    },
    'en':{
        'title':'Activate your account',
        'message':'The activation code for your account is : {}'
    }
}

archive_info={
    'ar':{
        'is_archive':True,
        'about_archive':'هنا ستجد جميع المقالات منذ تأسيس الموقع وتستطيع التنقل بينهم من خلال البحث أو استخدام أحد التصنيفات الموجودة في الأسفل',
        'search_in_archive':'البحث في الأرشيف',
        'latest_articles':'أحدث المقالات المؤرشفة',
        'most_read_articles':'أكثر المقالات قراءة',
        'most_rated_articles':'أكثر المقالات تقييما',
        'fields':'المجالات',
        'authors':'أكثر الكتاب كتابة'
    },
    'en':{
        'is_archive':True,
        'about_archive':'Here will find all articles from the beginning, You can navigate into articles using the search or choose one of below filters ',
        'search_in_archive':'Search In Archive',
        'latest_articles':'Latest Articles',
        'most_read_articles':'Most Read Articles',
        'most_rated_articles':'Most Rated Articles',
        'fields':'Fields',
        'authors':'Most Writers worte articles'
    },
}








#nufinished yet



            


