# Generated by Django 2.1.1 on 2018-12-14 04:36

from django.db import migrations, models
import django.db.models.deletion
import scientificJournalism.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name_plural': 'Admin',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('VIDEO', 'video'), ('AUDIO', 'audio'), ('IMAGE', 'image'), ('TEXT', 'text')], max_length=7)),
                ('field_en', models.CharField(choices=[('HEALTH', 'health'), ('IT', 'Information Technology'), ('ECOLOGY', 'Ecology'), ('ORGANISMS', 'Organisms'), ('NATURE', 'Nature and the universe'), ('CHEMICAL', 'Chemicals'), ('MATH', 'Math'), ('ENGINEERING', 'Engineering')], max_length=30)),
                ('field_ar', models.CharField(choices=[('HEALTH', 'الصحة'), ('IT', 'تقنية المعلومات'), ('ECOLOGY', 'البيئة'), ('ORGANISMS', 'الحياة'), ('NATURE', 'الكون و الطبيعة'), ('CHEMICAL', 'الكيميائيات'), ('MATH', 'الرياضيات'), ('ENGINEERING', 'هندسيات')], max_length=30)),
                ('cover_image', models.ImageField(upload_to='Cover Articles Images/%Y/%m/%d')),
                ('title_ar', models.CharField(blank=True, max_length=50, null=True)),
                ('title_en', models.CharField(blank=True, max_length=50, null=True)),
                ('brief_of_article_en', models.TextField(blank=True, null=True)),
                ('brief_of_article_ar', models.TextField(blank=True, null=True)),
                ('context_en', models.TextField(blank=True, null=True)),
                ('context_ar', models.TextField(blank=True, null=True)),
                ('submit_date', models.DateTimeField(auto_now_add=True)),
                ('article_status_en', models.CharField(choices=[('REJECTED', 'rejected'), ('SUBMITTED', 'submitted'), ('ASSIGNED', 'assigned'), ('REVIEWED', 'reviewed'), ('FINAL_REVIEWED', 'final_reviewed'), ('WITH_REVIEWER', 'with reviewer'), ('ONLINE', 'online'), ('EDITORIAL', 'editorial'), ('ARCHIVED', 'archived')], default='SUBMITTED', max_length=15)),
                ('article_status_ar', models.CharField(choices=[('REJECTED', 'مرفوض'), ('SUBMITTED', 'عند رئيس التحرير'), ('ASSIGNED', 'تحت التحرير'), ('REVIEWED', 'تمت مراجعته'), ('FINAL_REVIEWED', 'تمت المراجعة النهائية'), ('WITH_REVIEWER', 'عند المراجعين'), ('ONLINE', 'منشور'), ('EDITORIAL', 'افتتاحية'), ('ARCHIVED', 'مؤرشف')], default='SUBMITTED', max_length=15)),
                ('price', models.BooleanField(default=False)),
                ('is_editorial', models.BooleanField(default=False)),
                ('publishing_date', models.DateTimeField(blank=True, null=True)),
                ('number_of_views', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Article_Revision',
            fields=[
                ('article_revision_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('assign_date', models.DateTimeField(auto_now_add=True)),
                ('AE_comment', models.TextField(blank=True, null=True, verbose_name='Associate Editor Comment')),
                ('invite_date', models.DateTimeField(blank=True, null=True)),
                ('R_comment', models.TextField(blank=True, null=True, verbose_name='Reviewer Comment')),
                ('AE_recommendation', models.CharField(blank=True, choices=[('ACCEPT', 'accept'), ('REJECT', 'reject')], max_length=7, null=True, verbose_name='Associate Editor Recommendation')),
            ],
            options={
                'verbose_name_plural': 'Article_Revision',
            },
        ),
        migrations.CreateModel(
            name='Associate_Editor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Associate Editor',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('comment_content', models.TextField()),
                ('article_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scientificJournalism.Article')),
            ],
            options={
                'verbose_name_plural': 'Comment',
            },
        ),
        migrations.CreateModel(
            name='EBM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=256)),
                ('specialty_en', models.CharField(choices=[('HEALTH', 'health'), ('IT', 'Information Technology'), ('ECOLOGY', 'Ecology'), ('ORGANISMS', 'Organisms'), ('NATURE', 'Nature and the universe'), ('CHEMICAL', 'Chemicals'), ('MATH', 'Math'), ('ENGINEERING', 'Engineering')], max_length=20)),
                ('specialty_ar', models.CharField(choices=[('HEALTH', 'الصحة'), ('IT', 'تقنية المعلومات'), ('ECOLOGY', 'البيئة'), ('ORGANISMS', 'الحياة'), ('NATURE', 'الكون و الطبيعة'), ('CHEMICAL', 'الكيميائيات'), ('MATH', 'الرياضيات'), ('ENGINEERING', 'هندسيات')], max_length=20)),
                ('account_status_en', models.CharField(choices=[('ONLINE', 'online'), ('FREEZE', 'freeze')], max_length=7)),
                ('account_status_ar', models.CharField(choices=[('ONLINE', 'نشط'), ('FREEZE', 'مجمد')], max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Editorial Board Member',
            },
        ),
        migrations.CreateModel(
            name='Editor_in_Chief',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EIC_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scientificJournalism.EBM')),
            ],
            options={
                'verbose_name_plural': 'Editor in Chief',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('EIC_comment', models.TextField(blank=True, null=True, verbose_name='Editor in Chief Comment')),
                ('final_decision', models.CharField(choices=[('ACCEPT', 'accept'), ('REJECT', 'reject')], max_length=7)),
                ('EIC_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scientificJournalism.Editor_in_Chief', verbose_name='Editor in Chief ID')),
                ('article_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scientificJournalism.Article')),
            ],
            options={
                'verbose_name_plural': 'Editor in Chief Feedback',
            },
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('format', models.CharField(choices=[('VIDEO', 'video'), ('AUDIO', 'audio'), ('IMAGE', 'image'), ('TEXT', 'text')], max_length=7)),
                ('content', models.FileField(blank=True, null=True, upload_to=scientificJournalism.models.multimedia_directory_path)),
                ('aritcle_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scientificJournalism.Article')),
            ],
            options={
                'verbose_name_plural': 'Multimedia',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('package_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('package_name_en', models.CharField(max_length=50)),
                ('package_name_ar', models.CharField(max_length=50)),
                ('pakage_description_en', models.TextField()),
                ('pakage_description_ar', models.TextField()),
                ('duration', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('package_status_en', models.CharField(choices=[('ACTIVE', 'active'), ('INACTIVE', 'inactive')], default='INACTIVE', max_length=10)),
                ('package_status_ar', models.CharField(choices=[('ACTIVE', 'نشط'), ('INACTIVE', 'غير نشط')], default='INACTIVE', max_length=10)),
                ('admin_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scientificJournalism.Admin')),
            ],
            options={
                'verbose_name_plural': 'Package',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchase_ID', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('download_code', models.CharField(max_length=50)),
                ('article_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scientificJournalism.Article')),
            ],
            options={
                'verbose_name_plural': 'Purchase',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('rate_ID', models.BigAutoField(primary_key=True, serialize=False, verbose_name='rating ID')),
                ('subscriber_rating', models.IntegerField()),
                ('article_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scientificJournalism.Article')),
            ],
            options={
                'verbose_name_plural': 'Rating',
            },
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=256)),
                ('specialty_en', models.CharField(choices=[('HEALTH', 'health'), ('IT', 'Information Technology'), ('ECOLOGY', 'Ecology'), ('ORGANISMS', 'Organisms'), ('NATURE', 'Nature and the universe'), ('CHEMICAL', 'Chemicals'), ('MATH', 'Math'), ('ENGINEERING', 'Engineering')], max_length=20)),
                ('specialty_ar', models.CharField(choices=[('HEALTH', 'الصحة'), ('IT', 'تقنية المعلومات'), ('ECOLOGY', 'البيئة'), ('ORGANISMS', 'الحياة'), ('NATURE', 'الكون و الطبيعة'), ('CHEMICAL', 'الكيميائيات'), ('MATH', 'الرياضيات'), ('ENGINEERING', 'هندسيات')], max_length=20)),
                ('workplace', models.CharField(max_length=50)),
                ('account_status_en', models.CharField(choices=[('ONLINE', 'online'), ('FREEZE', 'freeze')], max_length=7)),
                ('account_status_ar', models.CharField(choices=[('ONLINE', 'نشط'), ('FREEZE', 'مجمد')], max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Reviewer',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='article price(S.R.)')),
                ('online_duration', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='online duration(days)')),
                ('editorial_duration', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='editorial duration(days)')),
            ],
            options={
                'verbose_name_plural': 'Setting',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=256)),
                ('picture', models.ImageField(upload_to='writer_&_subscribers_pic/%Y/%m/%d')),
            ],
            options={
                'verbose_name_plural': 'Subscriber',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('subscription_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('subscription_status_en', models.CharField(choices=[('ACTIVE', 'active'), ('INACTIVE', 'inactive')], max_length=10)),
                ('subscription_status_ar', models.CharField(choices=[('ACTIVE', 'نشط'), ('INACTIVE', 'غير نشط')], max_length=10)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('package_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scientificJournalism.Package')),
                ('subscriber_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scientificJournalism.Subscriber')),
            ],
            options={
                'verbose_name_plural': 'Subscription',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ID', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('birthdate', models.DateField()),
                ('gender_en', models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female')], max_length=6)),
                ('gender_ar', models.CharField(choices=[('MALE', 'ذكر'), ('FEMALE', 'أنثى')], max_length=6)),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('phone_number', models.BigIntegerField()),
                ('country', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=20)),
                ('activation', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'User',
            },
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=256)),
                ('specialty_en', models.CharField(choices=[('HEALTH', 'health'), ('IT', 'Information Technology'), ('ECOLOGY', 'Ecology'), ('ORGANISMS', 'Organisms'), ('NATURE', 'Nature and the universe'), ('CHEMICAL', 'Chemicals'), ('MATH', 'Math'), ('ENGINEERING', 'Engineering')], max_length=20)),
                ('specialty_ar', models.CharField(choices=[('HEALTH', 'الصحة'), ('IT', 'تقنية المعلومات'), ('ECOLOGY', 'البيئة'), ('ORGANISMS', 'الحياة'), ('NATURE', 'الكون و الطبيعة'), ('CHEMICAL', 'الكيميائيات'), ('MATH', 'الرياضيات'), ('ENGINEERING', 'هندسيات')], max_length=20)),
                ('workplace', models.CharField(max_length=50)),
                ('account_status_en', models.CharField(choices=[('ONLINE', 'online'), ('FREEZE', 'freeze')], default='FREEZE', max_length=7)),
                ('account_status_ar', models.CharField(choices=[('ONLINE', 'نشط'), ('FREEZE', 'مجمد')], default='FREEZE', max_length=7)),
                ('picture', models.ImageField(upload_to='writer_&_subscribers_pic/%Y/%m/%d')),
                ('writer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scientificJournalism.User')),
            ],
            options={
                'verbose_name_plural': 'Wirter',
            },
        ),
        migrations.AddField(
            model_name='subscriber',
            name='subscriber_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scientificJournalism.User'),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='reviewer_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scientificJournalism.User'),
        ),
        migrations.AddField(
            model_name='rate',
            name='subscriber_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scientificJournalism.Subscriber'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='writer_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scientificJournalism.Writer'),
        ),
        migrations.AddField(
            model_name='ebm',
            name='EBM_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scientificJournalism.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='subscriber_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scientificJournalism.Subscriber'),
        ),
        migrations.AddField(
            model_name='associate_editor',
            name='AE_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scientificJournalism.EBM'),
        ),
        migrations.AddField(
            model_name='article_revision',
            name='AE_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scientificJournalism.Associate_Editor', verbose_name='Associate Editor'),
        ),
        migrations.AddField(
            model_name='article_revision',
            name='EIC_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scientificJournalism.Editor_in_Chief', verbose_name='Editor in Chief ID'),
        ),
        migrations.AddField(
            model_name='article_revision',
            name='article_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scientificJournalism.Article'),
        ),
        migrations.AddField(
            model_name='article_revision',
            name='reviewer_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scientificJournalism.Reviewer'),
        ),
        migrations.AddField(
            model_name='article',
            name='writer_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scientificJournalism.Writer'),
        ),
        migrations.AddField(
            model_name='admin',
            name='admin_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scientificJournalism.User'),
        ),
    ]
